# Generated by Django 4.2.2 on 2023-06-18 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='heading',
            new_name='name',
        ),
    ]
